# Generated by Django 2.2.3 on 2019-07-15 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('nickname', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book_in_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('size', models.IntegerField()),
                ('link', models.TextField()),
                ('download_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('date_of_registration', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserInterfaceapp.Book_in_library')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserInterfaceapp.Category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserInterfaceapp.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='book_in_library',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserInterfaceapp.Profile'),
        ),
        migrations.CreateModel(
            name='Book_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserInterfaceapp.Book_in_library')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserInterfaceapp.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Book_author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserInterfaceapp.Author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserInterfaceapp.Book_in_library')),
            ],
        ),
    ]
