# Generated by Django 2.2.3 on 2019-07-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterfaceapp', '0003_auto_20190717_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklist',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='booklist',
            old_name='category_id',
            new_name='category',
        ),
    ]
