# Generated by Django 2.2.3 on 2019-07-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterfaceapp', '0005_auto_20190718_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_in_library',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
