# Generated by Django 2.2.3 on 2019-07-19 10:28

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'category.json', app_label='UserInterfaceapp')


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterfaceapp', '0006_auto_20190718_1544'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
